### ISSUE TITLE
Implement transitionPeriod for bin chart

### ISSUE THREAD

**Issue by anasdeis** [klaframboise/Treeflow.js#41]
Implement transitionPeriod and add the customization option for it:
**transitionPeriod**: number (seconds, optional, default = 0)
When provided in conjunction with count or average mode, the transitionPeriod is used to determine how long a device contributes to its previous bin after it has moved to a different bin. When transitionPeriod is 0, a device can never contribute to more than one bin at a time.

**Comment by anasdeis** [comment]
The transition period for bin chart is very hard to predict. When I receive an array with updates to existing devices, the first data value of the update might put two devices with the same deviceID and different x-y values apart (unless it is a new device, then it is directly added and we don't need the transition period). The next deviceId from the emitted array of updates can then put them back together in the same bin as we recategorize the number of bins dynamically every time a value is pushed to the array or deleted from the array of data, and then for the next deviceId from the same update array would put them back apart. It would then be required to check at every step for the bin computation that no two devices belong to the same bin, but even then it might just be temporary as the next updated value could put them apart when bins are recategorized and the range of either x or y axis, or both axes changed. It could also be that by the end of the If this is an accurate rendering of the transition period of the bin chart, it makes it extremely difficult to be implemented. I am also afraid it would slow it down considerably. Moreover, I do not see the real need for a transition period for the bin chart. @klaframboise

**Comment by klaframboise** [comment]
See comment from @anasdeis
