### ISSUE TITLE
Write public facing usage documentation

### ISSUE THREAD

**Issue by klaframboise** [klaframboise/Treeflow.js#5]
We need to write proper usage documentation in order to make this visualization framework more accessible. Sub issues should be created once we are ready to divide to documentation writing work.

**Comment by anasdeis** [comment]
![Package Directory](https://user-images.githubusercontent.com/35753718/93250779-4e8d6880-f761-11ea-8b20-1e82a66d1c2d.PNG)
Package Directory

**Comment by klaframboise** [comment]
See wiki.

**Comment by anasdeis** [comment]
![Package Directory](https://user-images.githubusercontent.com/35753718/101434934-78c27280-38d9-11eb-9195-2d5df10c50c6.png)
Updated package directory
